/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TPrFalso extends Token
{
    public TPrFalso()
    {
        super.setText("falso");
    }

    public TPrFalso(int line, int pos)
    {
        super.setText("falso");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPrFalso(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPrFalso(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPrFalso text.");
    }
}
