/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TPrFim extends Token
{
    public TPrFim()
    {
        super.setText("fim");
    }

    public TPrFim(int line, int pos)
    {
        super.setText("fim");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPrFim(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPrFim(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPrFim text.");
    }
}
