/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TPrVerdadeiro extends Token
{
    public TPrVerdadeiro()
    {
        super.setText("verdadeiro");
    }

    public TPrVerdadeiro(int line, int pos)
    {
        super.setText("verdadeiro");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPrVerdadeiro(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPrVerdadeiro(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPrVerdadeiro text.");
    }
}
