/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TUnderline extends Token
{
    public TUnderline()
    {
        super.setText("_");
    }

    public TUnderline(int line, int pos)
    {
        super.setText("_");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TUnderline(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTUnderline(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TUnderline text.");
    }
}
